baseURL = "https://northes.io/"
languageCode = "zh-cn"
title = "Northes"
theme = "hugo-tania"
enableRobotsTXT = true
enableGitInfo = false

[pagination]
pzgerSize = 10

[params]
titleEmoji = "ğŸ˜ƒ"
siteKeyword = "northes,Northes,blog,åšå®¢"
siteDesc = "Northes's Blog,Northesçš„åšå®¢ã€‚è®°å½•å­¦ä¹ ç¬”è®°ä»¥åŠè¿‡ç¨‹ä¸­è¸©è¿‡çš„å‘"
siteAuthor = "Northes"

[menu]
header = [
    #    { name = "Articles", url = "/articles/", weight = 1 },
    { name = "Tags", url = "/tags/", weight = 2 },
    { name = "Projects", url = "/projects/", weight = 3 },
    { name = "About", url = "/about/", weight = 4 },
]


[markup.highlight]
noClasses = false
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
