baseURL = "https://northes.co/"
languageCode = "zh-cn"
title = "Northes"
theme = "hugo-tania"
enableRobotsTXT = true
paginate = 10
enableGitInfo = true

[params]
titleEmoji = "ðŸ˜ƒ"
siteKeyword = "northes,Northes,blog"
siteDesc = "Northes's Blog"
siteAuthor = "Northes"

[menu]
header = [
#    { name = "Articles", url = "/articles/", weight = 1 },
#    { name = "Tags", url = "/tags/", weight = 2 },
    { name = "Projects", url = "/projects/", weight = 3 },
    { name = "About", url = "/about/", weight = 4 },
]


[markup.highlight]
noClasses = false
lineNos = true

[markup.goldmark.renderer]
unsafe = true